config/routes.rb
Rails.application.routes.draw do
  resources :urls, except: [:destroy, :update, :index, :edit]

  root 'urls#new'
  get ':id' => 'urls#redirect'

  namespace :api do
    namespace :v1 do
      resources :urls, only: :show do
        resources :stats, only: :index
      end
    end
  end

end

app/models/stat.rb
class Stat < ActiveRecord::Base
	belongs_to :url
end

app/models/url.rb
class Url < ActiveRecord::Base
	has_many :stats
	validates :short_url, presence: true
	validates :short_url, uniqueness: true
	validates :short_url, exclusion: { in: %w(urls stats api) }
	validates :original_url, presence: true
	validates :original_url, uniqueness: { scope: :short_url, message: "short url already exists." }
	validates :original_url, format: { with: URI.regexp }, if: Proc.new { |a| a.original_url.present? }
	validates :short_url, format: { with: /\A[-a-z]+\Z/ }

	BASE_DOMAIN = nil #using root domain if nil

	delegate :redirection, to: :url_redirection

	def url_redirection
		UrlRedirection.new self
	end

	def redirected
		stats.count
	end
end

app/models/url_redirection.rb
class UrlRedirection
	attr_accessor :url

	def initialize(url)
		@url = url
	end

	def redirection_url
		url.original_url
	end

	def redirection(request)
		create_stat(request)
		return redirection_url
	end

	def create_stat(request)
		url.stats.create(
			user_agent: request.user_agent,
			ip_address: request.remote_ip,
			referrer_url: request.referer
		)
	end
	
end

app/controllers/api/v1/stats_controller.rb
class API::V1::StatsController < ApplicationController
  before_action :set_url, only: [:index]

  def index
    render json: @url.to_json(include: { stats: { except: :url_id } }, methods: :redirected)
  end

  private
    def set_url
      @url = Url.find_by_short_url(params[:url_id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :redirect]

  def show
  end

  def new
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to url_url(@url.short_url), notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  def redirect
    if @url
      redirect_to @url.redirection(request), :status => :moved_permanently
    else
      redirect_to '/', notice: "there no any redirection for vanity #{params[:id]}"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find_by_short_url(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:short_url, :original_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
	def url_link url
		link = base_domain + url.short_url
		link_to link, link, target: '_blank'
	end

  def base_domain
    Url::BASE_DOMAIN || root_url
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/_form.html.slim
= form_for(@url) do |f|
  - if @url.errors.any?
    #error_explanation
      h2 #{pluralize(@url.errors.count, "error")} prohibited this url from being saved:
      ul
        - @url.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :short_url
    br
    = base_domain
    = f.text_field :short_url
  .field
    => f.label :original_url
    | (should include http:// or https://)
    br
    = f.text_area :original_url
  .actions
    = f.submit

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form' %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Urls</h1>

<table>
  <thead>
    <tr>
      <th>Short url</th>
      <th>Original url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url_link url %></td>
        <td><%= url.original_url %></td>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.slim
h2 URL Shortener

p Please input your short and original URL

= render 'form'

app/views/urls/show.html.slim
p#notice = notice

.link.short-url
  p Your short URL link:
  p = url_link @url
.link.original-url
  p Your Original URL link:
  p = @url.original_url

= link_to 'Create another one', new_url_path